### ISSUE TITLE
"disabled checked" incorrect color for Slider B and Slider B flat

### ISSUE THREAD

**Issue by gwhenne** [kleinejan/titatoggle#24]
See it here:
http://kleinejan.github.io/titatoggle/

It should be gray, not green.

![screen shot 2017-04-12 at 11 54 18 am](https://cloud.githubusercontent.com/assets/489708/24967048/ce3437f6-1f76-11e7-951c-5e826827ffbe.png)

**Comment by kleinejan** [comment]
Fixed

**Comment by gwhenne** [comment]
Perfect - thank you for the fast fix!

**Comment by mtnbrit** [comment]
Hi, I found that it works for the green Default appearance, but still doesn't work for the blue Info appearance, I didn't check the others...
